#!/usr/bin/env python3
"""Generate data/named-parts.json — curated lab / bench parts."""

from __future__ import annotations

import json
from pathlib import Path

def p(name, category, **kw):
    item = {
        "name": name,
        "category": category,
        "package": kw.get("package", ""),
        "mpn": kw.get("mpn", ""),
        "brand": kw.get("brand", ""),
        "sku": kw.get("sku", ""),
        "notes": kw.get("notes", ""),
        "source": "named",
        "popular": bool(kw.get("popular", False)),
    }
    return item


def main():
    parts = []

    boards = [
        p("ESP32 DevKit V1", "board", mpn="ESP32-DEVKIT", brand="Espressif", popular=True),
        p("ESP32-S3 DevKitC", "board", mpn="ESP32-S3-DevKitC-1", brand="Espressif", popular=True),
        p("ESP32-C3 SuperMini", "board", mpn="ESP32-C3", brand="Espressif"),
        p("ESP32-C6 DevKit", "board", mpn="ESP32-C6-DevKitC-1", brand="Espressif"),
        p("ESP8266 NodeMCU", "board", mpn="NodeMCU-32", brand="Espressif"),
        p("Wemos D1 Mini", "board", mpn="D1-MINI"),
        p("Raspberry Pi 5 8GB", "board", mpn="RPi5-8GB", brand="Raspberry Pi", popular=True),
        p("Raspberry Pi 5 4GB", "board", mpn="RPi5-4GB", brand="Raspberry Pi"),
        p("Raspberry Pi 4 4GB", "board", mpn="RPi4-4GB", brand="Raspberry Pi"),
        p("Raspberry Pi 4 8GB", "board", mpn="RPi4-8GB", brand="Raspberry Pi"),
        p("Raspberry Pi Zero 2 W", "board", mpn="RPi-Zero-2W", brand="Raspberry Pi", popular=True),
        p("Raspberry Pi Pico", "board", mpn="RP2040-Pico", brand="Raspberry Pi", popular=True),
        p("Raspberry Pi Pico W", "board", mpn="RP2040-Pico-W", brand="Raspberry Pi", popular=True),
        p("Raspberry Pi Pico 2", "board", mpn="RP2350-Pico-2", brand="Raspberry Pi"),
        p("Arduino Uno R3", "board", mpn="A000066", brand="Arduino", popular=True),
        p("Arduino Nano", "board", mpn="A000005", brand="Arduino", popular=True),
        p("Arduino Nano Every", "board", brand="Arduino"),
        p("Arduino Mega 2560", "board", mpn="A000067", brand="Arduino"),
        p("Arduino Micro", "board", brand="Arduino"),
        p("Seeed XIAO ESP32-S3", "board", brand="Seeed"),
        p("Seeed XIAO RP2040", "board", brand="Seeed"),
        p("Seeed XIAO nRF52840", "board", brand="Seeed"),
        p("STM32 Blue Pill", "board", mpn="STM32F103C8T6", popular=True),
        p("STM32 Black Pill", "board", mpn="STM32F411CEU6"),
        p("Teensy 4.0", "board", brand="PJRC"),
        p("Teensy 4.1", "board", brand="PJRC"),
        p("BBC micro:bit", "board"),
        p("Adafruit Feather M4", "board", brand="Adafruit"),
        p("Adafruit QT Py", "board", brand="Adafruit"),
        p("ESP32-CAM", "board", mpn="AI-Thinker ESP32-CAM"),
        p("LilyGO T-Display", "board", brand="LilyGO"),
        p("LilyGO T-Display S3", "board", brand="LilyGO"),
    ]
    parts += boards

    mcus = [
        p("ATmega328P-PU", "mcu", package="DIP-28", mpn="ATMEGA328P-PU", brand="Microchip", popular=True),
        p("ATmega328P-AU", "mcu", package="TQFP-32", mpn="ATMEGA328P-AU", brand="Microchip"),
        p("ATtiny85-20PU", "mcu", package="DIP-8", mpn="ATTINY85-20PU", brand="Microchip", popular=True),
        p("ATtiny1614", "mcu", package="SOIC-14", brand="Microchip"),
        p("RP2040", "mcu", package="QFN-56", mpn="RP2040", brand="Raspberry Pi", popular=True),
        p("RP2350", "mcu", package="QFN", mpn="RP2350", brand="Raspberry Pi"),
        p("ESP32-WROOM-32E", "mcu", package="SMD module", mpn="ESP32-WROOM-32E", brand="Espressif", popular=True),
        p("ESP32-WROOM-32UE", "mcu", package="SMD module", brand="Espressif"),
        p("ESP32-S3-WROOM-1", "mcu", package="SMD module", brand="Espressif"),
        p("ESP32-C3-WROOM-02", "mcu", package="SMD module", brand="Espressif"),
        p("STM32F103C8T6", "mcu", package="LQFP-48", mpn="STM32F103C8T6", brand="ST", popular=True),
        p("STM32F411CEU6", "mcu", package="UFQFPN-48", mpn="STM32F411CEU6", brand="ST"),
        p("STM32G030F6P6", "mcu", package="TSSOP-20", brand="ST"),
        p("nRF52840", "mcu", brand="Nordic"),
        p("CH32V003F4P6", "mcu", package="TSSOP-20", brand="WCH"),
        p("CH340G USB-UART", "ic", package="SOIC-16", mpn="CH340G", popular=True),
        p("CH340C USB-UART", "ic", package="SOIC-16", mpn="CH340C"),
        p("CP2102 USB-UART", "ic", package="QFN-28", mpn="CP2102"),
        p("FT232RL USB-UART", "ic", package="SSOP-28", mpn="FT232RL", brand="FTDI"),
    ]
    parts += mcus

    ics = [
        p("NE555P", "ic", package="DIP-8", mpn="NE555P", popular=True),
        p("LM358P", "ic", package="DIP-8", mpn="LM358P", popular=True),
        p("LM324N", "ic", package="DIP-14", mpn="LM324N"),
        p("TL072", "ic", package="DIP-8", mpn="TL072"),
        p("LM393", "ic", package="DIP-8"),
        p("LM311", "ic", package="DIP-8"),
        p("LM386", "ic", package="DIP-8"),
        p("UA741", "ic", package="DIP-8"),
        p("OP07", "ic", package="DIP-8"),
        p("74HC00", "ic", package="DIP-14"),
        p("74HC02", "ic", package="DIP-14"),
        p("74HC04", "ic", package="DIP-14"),
        p("74HC08", "ic", package="DIP-14"),
        p("74HC14", "ic", package="DIP-14"),
        p("74HC32", "ic", package="DIP-14"),
        p("74HC73", "ic", package="DIP-14"),
        p("74HC86", "ic", package="DIP-14"),
        p("74HC125", "ic", package="DIP-14"),
        p("74HC138", "ic", package="DIP-16"),
        p("74HC165", "ic", package="DIP-16"),
        p("74HC595", "ic", package="DIP-16", popular=True),
        p("74HC4051", "ic", package="DIP-16"),
        p("74HC4066", "ic", package="DIP-14"),
        p("CD4017", "ic", package="DIP-16"),
        p("CD4060", "ic", package="DIP-16"),
        p("CD4093", "ic", package="DIP-14"),
        p("MAX232", "ic", package="DIP-16"),
        p("MAX485", "ic", package="DIP-8"),
        p("PC817 optocoupler", "ic", package="DIP-4", popular=True),
        p("6N137 optocoupler", "ic", package="DIP-8"),
        p("24C256 EEPROM", "ic", package="DIP-8"),
        p("DS1307 RTC", "ic", package="DIP-8"),
        p("DS3231 RTC", "ic", package="SOIC-16", popular=True),
        p("AMS1117-3.3", "power", package="SOT-223", mpn="AMS1117-3.3", popular=True),
        p("AMS1117-5.0", "power", package="SOT-223", mpn="AMS1117-5.0"),
        p("LM7805", "power", package="TO-220", mpn="L7805CV", popular=True),
        p("LM7812", "power", package="TO-220", mpn="L7812CV"),
        p("LM317T", "power", package="TO-220", popular=True),
        p("XL4015 buck module IC", "power", package="TO-263"),
        p("MP1584EN", "power", package="SOIC-8"),
        p("TP4056", "power", package="SOP-8", popular=True),
        p("DW01A", "power", package="SOT-23-6"),
        p("FS8205A", "transistor", package="TSSOP-8"),
        p("ULN2003A", "ic", package="DIP-16"),
        p("L293D", "ic", package="DIP-16"),
        p("L298N", "ic", package="Multiwatt-15"),
        p("SN65HVD230", "ic", package="SOIC-8"),
        p("MCP3008", "ic", package="DIP-16"),
        p("ADS1115", "ic", package="MSOP-10"),
        p("INA219", "ic", package="SOT-23 / SOIC"),
        p("PCA9685", "ic", package="TSSOP-28"),
        p("MCP4725", "ic", package="SOT-23-6"),
        p("AT24C02", "ic", package="DIP-8"),
    ]
    parts += ics

    semis = [
        p("1N4148", "diode", package="DO-35", popular=True),
        p("1N4001", "diode", package="DO-41"),
        p("1N4007", "diode", package="DO-41", popular=True),
        p("1N5819 Schottky", "diode", package="DO-41", popular=True),
        p("1N5822 Schottky", "diode", package="DO-201"),
        p("SS14 Schottky", "diode", package="SMA"),
        p("SS34 Schottky", "diode", package="SMC"),
        p("BAT54S", "diode", package="SOT-23"),
        p("Zener 3.3V 0.5W", "diode", package="DO-35"),
        p("Zener 5.1V 0.5W", "diode", package="DO-35", popular=True),
        p("Zener 12V 0.5W", "diode", package="DO-35"),
        p("LED 5mm red", "led", package="5mm", popular=True),
        p("LED 5mm green", "led", package="5mm", popular=True),
        p("LED 5mm blue", "led", package="5mm"),
        p("LED 5mm yellow", "led", package="5mm"),
        p("LED 5mm white", "led", package="5mm"),
        p("LED 3mm red", "led", package="3mm"),
        p("LED 3mm green", "led", package="3mm"),
        p("WS2812B NeoPixel", "led", package="5050", popular=True),
        p("WS2812B strip 60/m", "led", package="strip", popular=True),
        p("SK6812 RGBW", "led", package="5050"),
        p("2N2222A", "transistor", package="TO-92", popular=True),
        p("2N3904", "transistor", package="TO-92", popular=True),
        p("2N3906", "transistor", package="TO-92"),
        p("BC547", "transistor", package="TO-92"),
        p("BC557", "transistor", package="TO-92"),
        p("S8050", "transistor", package="TO-92"),
        p("S8550", "transistor", package="TO-92"),
        p("IRF540N MOSFET", "transistor", package="TO-220", popular=True),
        p("IRFZ44N MOSFET", "transistor", package="TO-220"),
        p("IRF3205 MOSFET", "transistor", package="TO-220"),
        p("IRL7843 MOSFET", "transistor", package="TO-220"),
        p("AO3400 MOSFET", "transistor", package="SOT-23", popular=True),
        p("AO3401 MOSFET", "transistor", package="SOT-23"),
        p("2N7000 MOSFET", "transistor", package="TO-92"),
        p("BS170 MOSFET", "transistor", package="TO-92"),
        p("TIP120 Darlington", "transistor", package="TO-220"),
        p("TIP31C", "transistor", package="TO-220"),
        p("TIP32C", "transistor", package="TO-220"),
    ]
    parts += semis

    sensors = [
        p("DHT11", "sensor", popular=True),
        p("DHT22 / AM2302", "sensor", popular=True),
        p("DS18B20", "sensor", package="TO-92", popular=True),
        p("BMP280", "sensor"),
        p("BME280", "sensor", popular=True),
        p("MPU6050", "sensor", popular=True),
        p("MPU9250", "sensor"),
        p("HCSR04 ultrasonic", "sensor", popular=True),
        p("PIR HC-SR501", "sensor"),
        p("KY-038 sound", "sensor"),
        p("MQ-2 gas", "sensor"),
        p("MQ-135 air quality", "sensor"),
        p("TCS34725 color", "sensor"),
        p("VL53L0X ToF", "sensor"),
        p("HX711 load cell amp", "sensor"),
        p("ACS712 5A", "sensor"),
        p("ACS712 20A", "sensor"),
        p("INA219 current", "sensor"),
        p("MAX30102 pulse ox", "sensor"),
        p("RCWL-0516 radar", "sensor"),
        p("SW-420 vibration", "sensor"),
        p("Hall A3144", "sensor", package="TO-92"),
        p("Photoresistor GL5528", "sensor"),
        p("Thermistor 10k NTC", "sensor", popular=True),
        p("Soil moisture probe", "sensor"),
    ]
    parts += sensors

    modules = [
        p("nRF24L01+", "module", popular=True),
        p("HC-05 Bluetooth", "module", popular=True),
        p("HC-06 Bluetooth", "module"),
        p("HM-10 BLE", "module"),
        p("ESP-01", "module"),
        p("SX1278 LoRa 433", "module"),
        p("SX1276 LoRa 868/915", "module"),
        p("RFM95W LoRa", "module"),
        p("SIM800L", "module"),
        p("A9G GSM/GPS", "module"),
        p("NEO-6M GPS", "module", popular=True),
        p("NEO-8M GPS", "module"),
        p("SD card module", "module"),
        p("MicroSD breakout", "module"),
        p("Relay 5V 1ch", "module", popular=True),
        p("Relay 5V 2ch", "module"),
        p("Relay 5V 4ch", "module"),
        p("Relay 5V 8ch", "module"),
        p("SSR 5V", "module"),
        p("Logic level shifter 4ch", "module", popular=True),
        p("Logic level shifter 8ch", "module"),
        p("I2C multiplexer TCA9548A", "module"),
        p("PCA9685 16ch PWM", "module"),
        p("ADS1115 ADC module", "module"),
        p("DS3231 RTC module", "module", popular=True),
        p("AT24C32 EEPROM module", "module"),
        p("W5500 Ethernet", "module"),
        p("ENC28J60 Ethernet", "module"),
        p("PN532 NFC", "module"),
        p("RC522 RFID", "module", popular=True),
        p("Stepper A4988", "module", popular=True),
        p("Stepper DRV8825", "module"),
        p("Stepper TMC2209", "module"),
        p("L298N motor driver", "module", popular=True),
        p("TB6612FNG motor driver", "module"),
        p("MX1508 motor driver", "module"),
        p("SG90 servo", "module", popular=True),
        p("MG996R servo", "module"),
        p("28BYJ-48 stepper + ULN2003", "module"),
        p("Breadboard 830", "module", popular=True),
        p("Breadboard 400", "module"),
        p("Perfboard 5x7", "mechanical"),
        p("Perfboard 7x9", "mechanical"),
        p("Prototype PCB 2x8cm", "mechanical"),
    ]
    parts += modules

    displays = [
        p("SSD1306 OLED 128x64 0.96\"", "display", popular=True),
        p("SSD1306 OLED 128x32 0.91\"", "display"),
        p("SH1106 OLED 1.3\"", "display"),
        p("LCD 1602 I2C", "display", popular=True),
        p("LCD 2004 I2C", "display"),
        p("TFT 1.8\" ST7735", "display"),
        p("TFT 2.4\" ILI9341", "display"),
        p("TFT 3.5\" ILI9488", "display"),
        p("Nextion 2.4\"", "display"),
        p("TM1637 4-digit", "display"),
        p("MAX7219 8x8", "display"),
        p("MAX7219 8-digit", "display"),
        p("WS2812 8x8 matrix", "display"),
        p("E-paper 2.9\"", "display"),
    ]
    parts += displays

    connectors = [
        p("Pin header 2.54 40-pin M", "connector", popular=True),
        p("Pin header 2.54 40-pin F", "connector", popular=True),
        p("Dupont housing 1p", "connector"),
        p("Dupont housing 2p", "connector"),
        p("Dupont housing 3p", "connector"),
        p("Dupont crimp pin M", "connector"),
        p("Dupont crimp pin F", "connector"),
        p("JST-XH 2.54 2p", "connector"),
        p("JST-XH 2.54 3p", "connector"),
        p("JST-PH 2.0 2p", "connector"),
        p("JST-PH 2.0 4p", "connector"),
        p("JST-SH 1.0 4p", "connector"),
        p("USB-C receptacle 16p", "connector", popular=True),
        p("USB-C breakout", "connector"),
        p("Micro USB receptacle", "connector"),
        p("USB-A receptacle", "connector"),
        p("DC barrel 5.5x2.1 jack", "connector", popular=True),
        p("DC barrel 5.5x2.1 plug", "connector"),
        p("3.5mm jack stereo", "connector"),
        p("Terminal block 2p 5.08", "connector"),
        p("Terminal block 3p 5.08", "connector"),
        p("Screw terminal 5mm 2p", "connector"),
        p("DB9 male", "connector"),
        p("DB9 female", "connector"),
        p("RJ45 jack", "connector"),
        p("SMA female PCB", "connector"),
        p("u.FL / IPEX", "connector"),
        p("Banana jack", "connector"),
        p("Alligator clip pair", "connector"),
        p("IC socket DIP-8", "connector"),
        p("IC socket DIP-14", "connector"),
        p("IC socket DIP-16", "connector"),
        p("IC socket DIP-28", "connector"),
    ]
    parts += connectors

    tools = [
        p("Solder 60/40 0.8mm", "chemical", popular=True, notes="Sn60/Pb40"),
        p("Solder 63/37 0.6mm", "chemical", popular=True),
        p("Solder lead-free SAC305 0.8mm", "chemical"),
        p("Solder paste Sn63 leaded", "chemical", popular=True),
        p("Solder paste SAC305", "chemical"),
        p("Rosin flux paste", "chemical", popular=True),
        p("Flux pen no-clean", "chemical", popular=True),
        p("Flux paste no-clean", "chemical"),
        p("Desolder braid 2mm", "chemical", popular=True),
        p("Desolder braid 3mm", "chemical"),
        p("Desolder pump", "tool"),
        p("Isopropyl alcohol 99%", "chemical", popular=True),
        p("Isopropyl alcohol 70%", "chemical"),
        p("PCB cleaner", "chemical"),
        p("Thermal paste", "chemical"),
        p("Hot glue sticks", "chemical"),
        p("Cyanoacrylate CA glue", "chemical"),
        p("Kapton tape 10mm", "tool", popular=True),
        p("Kapton tape 20mm", "tool"),
        p("Electrical tape", "tool"),
        p("Solder tip T12-K", "tool"),
        p("Solder tip T12-D24", "tool"),
        p("Solder tip T12-I", "tool"),
        p("Solder tip 900M-T-I", "tool"),
        p("Solder tip 900M-T-K", "tool"),
        p("Helping hands", "tool"),
        p("PCB holder", "tool"),
        p("Tweezers ESD", "tool"),
        p("Flush cutters", "tool"),
        p("Wire stripper", "tool"),
        p("Multimeter probes", "tool"),
        p("Logic analyzer 8ch", "tool"),
        p("USB-TTL adapter", "tool", popular=True),
        p("ST-Link V2", "tool"),
        p("USBasp", "tool"),
        p("JTAG adapter", "tool"),
        p("Hot air nozzles set", "tool"),
        p("Solder fume filter", "tool"),
        p("ESD wrist strap", "tool"),
        p("Magnifier lamp spare bulb", "tool"),
        p("3D printer nozzle 0.4", "tool"),
        p("3D printer PTFE tube", "tool"),
    ]
    parts += tools

    wire = [
        p("Jumper wire M-M", "wire", popular=True),
        p("Jumper wire M-F", "wire", popular=True),
        p("Jumper wire F-F", "wire"),
        p("Silicone wire 24AWG red", "wire"),
        p("Silicone wire 24AWG black", "wire"),
        p("Silicone wire 22AWG red", "wire"),
        p("Silicone wire 22AWG black", "wire"),
        p("Hookup wire 22AWG solid kit", "wire", popular=True),
        p("Ribbon cable 10-way", "wire"),
        p("Ribbon cable 40-way", "wire"),
        p("Heat shrink 2mm", "wire", popular=True),
        p("Heat shrink 3mm", "wire"),
        p("Heat shrink 6mm", "wire"),
        p("Heat shrink kit assorted", "wire", popular=True),
        p("Sleeving PET 6mm", "wire"),
        p("Ferrules 0.75mm", "wire"),
        p("Cable ties 100mm", "wire"),
    ]
    parts += wire

    power = [
        p("18650 Li-ion cell", "power", popular=True),
        p("18650 holder 1s", "power"),
        p("18650 holder 2s", "power"),
        p("LiPo 3.7V 1000mAh", "power"),
        p("LiPo 3.7V 2000mAh", "power"),
        p("CR2032", "power", popular=True),
        p("CR2032 holder", "power"),
        p("9V battery", "power"),
        p("9V snap connector", "power"),
        p("AA alkaline", "power"),
        p("AAA alkaline", "power"),
        p("AA NiMH", "power"),
        p("USB-C PD trigger 5V", "power"),
        p("USB-C PD trigger 9V/12V", "power"),
        p("Buck module 5A XL4015", "power", popular=True),
        p("Buck module Mini360", "power"),
        p("Boost module MT3608", "power", popular=True),
        p("Buck-boost LM2596S", "power"),
        p("PicoPSU 12V", "power"),
        p("Meanwell 5V 5A PSU", "power"),
        p("USB charger 5V 2A", "power"),
        p("Fuse 5x20 1A", "power"),
        p("Fuse 5x20 2A", "power"),
        p("Fuse 5x20 5A", "power"),
        p("Polyfuse 500mA", "power"),
        p("Polyfuse 1A", "power"),
    ]
    parts += power

    mech = [
        p("M2 standoff 10mm", "mechanical"),
        p("M2.5 standoff 10mm", "mechanical"),
        p("M3 standoff 10mm", "mechanical", popular=True),
        p("M3 standoff 15mm", "mechanical"),
        p("M3 screw 6mm", "mechanical"),
        p("M3 screw 10mm", "mechanical"),
        p("M3 nut", "mechanical"),
        p("M2 screw 6mm", "mechanical"),
        p("Rubber feet", "mechanical"),
        p("Knobs 6mm shaft", "mechanical"),
        p("Switch tactile 6x6x5", "mechanical", popular=True),
        p("Switch tactile 6x6x8", "mechanical"),
        p("Switch tactile 12x12", "mechanical"),
        p("Rocker switch 21x15", "mechanical"),
        p("Toggle switch SPDT", "mechanical"),
        p("Slide switch SPDT", "mechanical"),
        p("Pushbutton 12mm metal", "mechanical"),
        p("Encoder EC11", "mechanical", popular=True),
        p("Potentiometer 10k linear", "mechanical", popular=True),
        p("Potentiometer 10k log", "mechanical"),
        p("Trimpot 10k 3296W", "mechanical", popular=True),
        p("Trimpot 1k 3296W", "mechanical"),
        p("Trimpot 100k 3296W", "mechanical"),
        p("Crystal 8MHz", "mechanical"),
        p("Crystal 16MHz", "mechanical", popular=True),
        p("Crystal 12MHz", "mechanical"),
        p("Crystal 32.768kHz", "mechanical"),
        p("Resonator 16MHz", "mechanical"),
        p("Ferrite bead 600Ω 0805", "mechanical"),
        p("Bead clamp ferrite", "mechanical"),
    ]
    parts += mech

    extra_passives = [
        p("Resistor kit E24 1/4W", "resistor", package="THT", popular=True),
        p("Resistor kit 0603 1%", "resistor", package="0603"),
        p("Capacitor kit ceramic 0805", "capacitor", package="0805", popular=True),
        p("Electrolytic kit 16/25/50V", "capacitor", package="electrolytic", popular=True),
        p("Inductor kit 0805", "inductor", package="0805"),
        p("100nF 50V 0805", "capacitor", package="0805", popular=True),
        p("10uF 16V 0805", "capacitor", package="0805"),
        p("22uF 16V electrolytic", "capacitor", package="electrolytic"),
        p("100uF 16V electrolytic", "capacitor", package="electrolytic", popular=True),
        p("470uF 16V electrolytic", "capacitor", package="electrolytic"),
        p("1000uF 16V electrolytic", "capacitor", package="electrolytic"),
        p("10kΩ 1/4W 1%", "resistor", package="THT 1/4W", popular=True),
        p("4.7kΩ 1/4W 1%", "resistor", package="THT 1/4W", popular=True),
        p("1kΩ 1/4W 1%", "resistor", package="THT 1/4W", popular=True),
        p("220Ω 1/4W 1%", "resistor", package="THT 1/4W", popular=True),
        p("330Ω 1/4W 5%", "resistor", package="THT 1/4W"),
        p("10kΩ 0603 1%", "resistor", package="0603", popular=True),
        p("4.7kΩ 0603 1%", "resistor", package="0603"),
        p("100nF 0603 50V", "capacitor", package="0603", popular=True),
    ]
    parts += extra_passives

    out = Path(__file__).resolve().parents[1] / "data" / "named-parts.json"
    out.write_text(json.dumps(parts, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {len(parts)} parts -> {out}")


if __name__ == "__main__":
    main()
